### ISSUE TITLE
[BUG] Error: Cannot find module './.env.json'

### ISSUE THREAD

**Issue by jkrauska** [FC-softwares/baseball-scoreboard#108]
**Describe the bug**
On initial checkout `npm start` expects env.json.

no clear instructions on what should be in this file.

creating a file with only "{}" in it seems to bypass this.

**To Reproduce**
Steps to reproduce the behaviour:
1. clone
2. npm i
3. npm start

**Expected behaviour**
npm start should cleanly start

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lucafano04** [comment]
Hi,
Thanks for letting us know about this issue, we are looking forward to making clear documentation about the configuration file, for now, it is better to just use the default example.env.json file.
The documentation will be added
