### ISSUE TITLE
[BUG] Main Board Still shows with 1920x1080 window.

### ISSUE THREAD

**Issue by jkrauska** [FC-softwares/baseball-scoreboard#109]
**Describe the bug**
When disabling the Main Board, the logos and score go off to the left, but the bases and innings just drop towards the bottom. 

**To Reproduce**
Steps to reproduce the behaviour:
1. In OBS setup Browser input
2. Disable Main
3. See Image drop to bottom.

**Expected behaviour**
Fully clears the screen?

**Screenshots**
<img width="722" alt="Screenshot 2023-10-13 at 1 01 47 PM" src="https://github.com/FC-softwares/baseball-scoreboard/assets/613548/5cc96e78-3b73-4e22-b4ce-86220dc68e68">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jkrauska** [comment]
Seems to get off screen in 1280x720

**Comment by lucafano04** [comment]
Hi,
Thanks for letting us know about this issue, we will find a way to change this behaviour shortly, in the meantime you could try to just resize the window to a smaller format and move the source on OBS where you like,
A fix will be coming shortly
