### ISSUE TITLE
[FEAT] Feature Request. - Third Strike Adds One Out, Starts Next Batter

### ISSUE THREAD

**Issue by jkrauska** [FC-softwares/baseball-scoreboard#110]
**Describe the bug**
If you have two strikes, and you hit strike again, it should increment Out by one and clear the count to set the next batter.

Similarly, if you have two outs, and hit third out, it should effectively hit "Auto Change Inning" to move the inning and advance.

One more case would be that if you have 3 balls, and you hit ball 4, it could put a runner on 1b.

I realize there are cases where these don't work perfectly. (dropped third strike rule)
But I feel like it could be an automation to reduce clickss overall.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lucafano04** [comment]
Hi,
Since this is a "small" feature request will be processed in a short time, probably the next version (V2.0.1) will include this feature.
I will personally work on this.
